// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.5
// source: Gateserver.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface Gateserver {
  unk1: boolean;
  assetBundleUrl: string;
  port: number;
  retcode: number;
  regionName: string;
  exResourceUrl: string;
  unk2: boolean;
  ip: string;
  luaUrl: string;
  privacyInGameUrl: string;
  gridFightGameRefCdnUrl: string;
  loginWhiteMsg: string;
  unk11: boolean;
  gameStartCustomerServiceUrl: string;
  unk3: boolean;
  unk4: boolean;
  unk10: boolean;
  unk5: boolean;
  unk6: boolean;
  unk14: boolean;
  unk13: boolean;
  unk7: boolean;
  unk8: boolean;
  unk15: boolean;
  unk16: boolean;
  ifixVersion: string;
  mdkResVersion: string;
  unk12: boolean;
  baseAssetBundleVersionUpdateUrl: string;
  ifixUrl: string;
  unk9: boolean;
  ClientSecretKey: string;
  ipv6Address: string;
  preDownload: string;
  rogueTournBuildRefApiReqColorHeaderValue: string;
  gridFightGameRefColorHeaderValue: string;
  rogueTournBuildRefApiReqColorHeaderKey: string;
  rogueTournBuildRefH5Url: string;
  rogueTournBuildRefStaticDataUrlPrefix: string;
  gridFightGameRefColorHeaderKey: string;
  customServiceUrl: string;
  gridFightGameRefH5Url: string;
  querySecurityFileUrl: string;
  teenagerPrivacyInGameUrl: string;
  thirdPrivacyInGameUrl: string;
  rogueMagicH5Url: string;
  userAgreementUrl: string;
  temporaryMaintenanceUrl: string;
  personalInformationInGameUrl: string;
}

function createBaseGateserver(): Gateserver {
  return {
    unk1: false,
    assetBundleUrl: "",
    port: 0,
    retcode: 0,
    regionName: "",
    exResourceUrl: "",
    unk2: false,
    ip: "",
    luaUrl: "",
    privacyInGameUrl: "",
    gridFightGameRefCdnUrl: "",
    loginWhiteMsg: "",
    unk11: false,
    gameStartCustomerServiceUrl: "",
    unk3: false,
    unk4: false,
    unk10: false,
    unk5: false,
    unk6: false,
    unk14: false,
    unk13: false,
    unk7: false,
    unk8: false,
    unk15: false,
    unk16: false,
    ifixVersion: "",
    mdkResVersion: "",
    unk12: false,
    baseAssetBundleVersionUpdateUrl: "",
    ifixUrl: "",
    unk9: false,
    ClientSecretKey: "",
    ipv6Address: "",
    preDownload: "",
    rogueTournBuildRefApiReqColorHeaderValue: "",
    gridFightGameRefColorHeaderValue: "",
    rogueTournBuildRefApiReqColorHeaderKey: "",
    rogueTournBuildRefH5Url: "",
    rogueTournBuildRefStaticDataUrlPrefix: "",
    gridFightGameRefColorHeaderKey: "",
    customServiceUrl: "",
    gridFightGameRefH5Url: "",
    querySecurityFileUrl: "",
    teenagerPrivacyInGameUrl: "",
    thirdPrivacyInGameUrl: "",
    rogueMagicH5Url: "",
    userAgreementUrl: "",
    temporaryMaintenanceUrl: "",
    personalInformationInGameUrl: "",
  };
}

export const Gateserver: MessageFns<Gateserver> = {
  encode(message: Gateserver, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.unk1 !== false) {
      writer.uint32(80).bool(message.unk1);
    }
    if (message.assetBundleUrl !== "") {
      writer.uint32(98).string(message.assetBundleUrl);
    }
    if (message.port !== 0) {
      writer.uint32(56).uint32(message.port);
    }
    if (message.retcode !== 0) {
      writer.uint32(112).uint32(message.retcode);
    }
    if (message.regionName !== "") {
      writer.uint32(74).string(message.regionName);
    }
    if (message.exResourceUrl !== "") {
      writer.uint32(90).string(message.exResourceUrl);
    }
    if (message.unk2 !== false) {
      writer.uint32(120).bool(message.unk2);
    }
    if (message.ip !== "") {
      writer.uint32(26).string(message.ip);
    }
    if (message.luaUrl !== "") {
      writer.uint32(50).string(message.luaUrl);
    }
    if (message.privacyInGameUrl !== "") {
      writer.uint32(5826).string(message.privacyInGameUrl);
    }
    if (message.gridFightGameRefCdnUrl !== "") {
      writer.uint32(7066).string(message.gridFightGameRefCdnUrl);
    }
    if (message.loginWhiteMsg !== "") {
      writer.uint32(346).string(message.loginWhiteMsg);
    }
    if (message.unk11 !== false) {
      writer.uint32(11520).bool(message.unk11);
    }
    if (message.gameStartCustomerServiceUrl !== "") {
      writer.uint32(6714).string(message.gameStartCustomerServiceUrl);
    }
    if (message.unk3 !== false) {
      writer.uint32(536).bool(message.unk3);
    }
    if (message.unk4 !== false) {
      writer.uint32(632).bool(message.unk4);
    }
    if (message.unk10 !== false) {
      writer.uint32(896).bool(message.unk10);
    }
    if (message.unk5 !== false) {
      writer.uint32(1472).bool(message.unk5);
    }
    if (message.unk6 !== false) {
      writer.uint32(1600).bool(message.unk6);
    }
    if (message.unk14 !== false) {
      writer.uint32(1664).bool(message.unk14);
    }
    if (message.unk13 !== false) {
      writer.uint32(3144).bool(message.unk13);
    }
    if (message.unk7 !== false) {
      writer.uint32(3632).bool(message.unk7);
    }
    if (message.unk8 !== false) {
      writer.uint32(4232).bool(message.unk8);
    }
    if (message.unk15 !== false) {
      writer.uint32(7432).bool(message.unk15);
    }
    if (message.unk16 !== false) {
      writer.uint32(7800).bool(message.unk16);
    }
    if (message.ifixVersion !== "") {
      writer.uint32(9426).string(message.ifixVersion);
    }
    if (message.mdkResVersion !== "") {
      writer.uint32(9906).string(message.mdkResVersion);
    }
    if (message.unk12 !== false) {
      writer.uint32(10208).bool(message.unk12);
    }
    if (message.baseAssetBundleVersionUpdateUrl !== "") {
      writer.uint32(11338).string(message.baseAssetBundleVersionUpdateUrl);
    }
    if (message.ifixUrl !== "") {
      writer.uint32(11906).string(message.ifixUrl);
    }
    if (message.unk9 !== false) {
      writer.uint32(13488).bool(message.unk9);
    }
    if (message.ClientSecretKey !== "") {
      writer.uint32(5770).string(message.ClientSecretKey);
    }
    if (message.ipv6Address !== "") {
      writer.uint32(15178).string(message.ipv6Address);
    }
    if (message.preDownload !== "") {
      writer.uint32(4346).string(message.preDownload);
    }
    if (message.rogueTournBuildRefApiReqColorHeaderValue !== "") {
      writer.uint32(9050).string(message.rogueTournBuildRefApiReqColorHeaderValue);
    }
    if (message.gridFightGameRefColorHeaderValue !== "") {
      writer.uint32(16258).string(message.gridFightGameRefColorHeaderValue);
    }
    if (message.rogueTournBuildRefApiReqColorHeaderKey !== "") {
      writer.uint32(2082).string(message.rogueTournBuildRefApiReqColorHeaderKey);
    }
    if (message.rogueTournBuildRefH5Url !== "") {
      writer.uint32(4170).string(message.rogueTournBuildRefH5Url);
    }
    if (message.rogueTournBuildRefStaticDataUrlPrefix !== "") {
      writer.uint32(3890).string(message.rogueTournBuildRefStaticDataUrlPrefix);
    }
    if (message.gridFightGameRefColorHeaderKey !== "") {
      writer.uint32(5346).string(message.gridFightGameRefColorHeaderKey);
    }
    if (message.customServiceUrl !== "") {
      writer.uint32(3674).string(message.customServiceUrl);
    }
    if (message.gridFightGameRefH5Url !== "") {
      writer.uint32(5234).string(message.gridFightGameRefH5Url);
    }
    if (message.querySecurityFileUrl !== "") {
      writer.uint32(15842).string(message.querySecurityFileUrl);
    }
    if (message.teenagerPrivacyInGameUrl !== "") {
      writer.uint32(14162).string(message.teenagerPrivacyInGameUrl);
    }
    if (message.thirdPrivacyInGameUrl !== "") {
      writer.uint32(10666).string(message.thirdPrivacyInGameUrl);
    }
    if (message.rogueMagicH5Url !== "") {
      writer.uint32(13778).string(message.rogueMagicH5Url);
    }
    if (message.userAgreementUrl !== "") {
      writer.uint32(14490).string(message.userAgreementUrl);
    }
    if (message.temporaryMaintenanceUrl !== "") {
      writer.uint32(13930).string(message.temporaryMaintenanceUrl);
    }
    if (message.personalInformationInGameUrl !== "") {
      writer.uint32(12098).string(message.personalInformationInGameUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Gateserver {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGateserver();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.unk1 = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.assetBundleUrl = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.port = reader.uint32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.retcode = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.regionName = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.exResourceUrl = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.unk2 = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ip = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.luaUrl = reader.string();
          continue;
        }
        case 728: {
          if (tag !== 5826) {
            break;
          }

          message.privacyInGameUrl = reader.string();
          continue;
        }
        case 883: {
          if (tag !== 7066) {
            break;
          }

          message.gridFightGameRefCdnUrl = reader.string();
          continue;
        }
        case 43: {
          if (tag !== 346) {
            break;
          }

          message.loginWhiteMsg = reader.string();
          continue;
        }
        case 1440: {
          if (tag !== 11520) {
            break;
          }

          message.unk11 = reader.bool();
          continue;
        }
        case 839: {
          if (tag !== 6714) {
            break;
          }

          message.gameStartCustomerServiceUrl = reader.string();
          continue;
        }
        case 67: {
          if (tag !== 536) {
            break;
          }

          message.unk3 = reader.bool();
          continue;
        }
        case 79: {
          if (tag !== 632) {
            break;
          }

          message.unk4 = reader.bool();
          continue;
        }
        case 112: {
          if (tag !== 896) {
            break;
          }

          message.unk10 = reader.bool();
          continue;
        }
        case 184: {
          if (tag !== 1472) {
            break;
          }

          message.unk5 = reader.bool();
          continue;
        }
        case 200: {
          if (tag !== 1600) {
            break;
          }

          message.unk6 = reader.bool();
          continue;
        }
        case 208: {
          if (tag !== 1664) {
            break;
          }

          message.unk14 = reader.bool();
          continue;
        }
        case 393: {
          if (tag !== 3144) {
            break;
          }

          message.unk13 = reader.bool();
          continue;
        }
        case 454: {
          if (tag !== 3632) {
            break;
          }

          message.unk7 = reader.bool();
          continue;
        }
        case 529: {
          if (tag !== 4232) {
            break;
          }

          message.unk8 = reader.bool();
          continue;
        }
        case 929: {
          if (tag !== 7432) {
            break;
          }

          message.unk15 = reader.bool();
          continue;
        }
        case 975: {
          if (tag !== 7800) {
            break;
          }

          message.unk16 = reader.bool();
          continue;
        }
        case 1178: {
          if (tag !== 9426) {
            break;
          }

          message.ifixVersion = reader.string();
          continue;
        }
        case 1238: {
          if (tag !== 9906) {
            break;
          }

          message.mdkResVersion = reader.string();
          continue;
        }
        case 1276: {
          if (tag !== 10208) {
            break;
          }

          message.unk12 = reader.bool();
          continue;
        }
        case 1417: {
          if (tag !== 11338) {
            break;
          }

          message.baseAssetBundleVersionUpdateUrl = reader.string();
          continue;
        }
        case 1488: {
          if (tag !== 11906) {
            break;
          }

          message.ifixUrl = reader.string();
          continue;
        }
        case 1686: {
          if (tag !== 13488) {
            break;
          }

          message.unk9 = reader.bool();
          continue;
        }
        case 721: {
          if (tag !== 5770) {
            break;
          }

          message.ClientSecretKey = reader.string();
          continue;
        }
        case 1897: {
          if (tag !== 15178) {
            break;
          }

          message.ipv6Address = reader.string();
          continue;
        }
        case 543: {
          if (tag !== 4346) {
            break;
          }

          message.preDownload = reader.string();
          continue;
        }
        case 1131: {
          if (tag !== 9050) {
            break;
          }

          message.rogueTournBuildRefApiReqColorHeaderValue = reader.string();
          continue;
        }
        case 2032: {
          if (tag !== 16258) {
            break;
          }

          message.gridFightGameRefColorHeaderValue = reader.string();
          continue;
        }
        case 260: {
          if (tag !== 2082) {
            break;
          }

          message.rogueTournBuildRefApiReqColorHeaderKey = reader.string();
          continue;
        }
        case 521: {
          if (tag !== 4170) {
            break;
          }

          message.rogueTournBuildRefH5Url = reader.string();
          continue;
        }
        case 486: {
          if (tag !== 3890) {
            break;
          }

          message.rogueTournBuildRefStaticDataUrlPrefix = reader.string();
          continue;
        }
        case 668: {
          if (tag !== 5346) {
            break;
          }

          message.gridFightGameRefColorHeaderKey = reader.string();
          continue;
        }
        case 459: {
          if (tag !== 3674) {
            break;
          }

          message.customServiceUrl = reader.string();
          continue;
        }
        case 654: {
          if (tag !== 5234) {
            break;
          }

          message.gridFightGameRefH5Url = reader.string();
          continue;
        }
        case 1980: {
          if (tag !== 15842) {
            break;
          }

          message.querySecurityFileUrl = reader.string();
          continue;
        }
        case 1770: {
          if (tag !== 14162) {
            break;
          }

          message.teenagerPrivacyInGameUrl = reader.string();
          continue;
        }
        case 1333: {
          if (tag !== 10666) {
            break;
          }

          message.thirdPrivacyInGameUrl = reader.string();
          continue;
        }
        case 1722: {
          if (tag !== 13778) {
            break;
          }

          message.rogueMagicH5Url = reader.string();
          continue;
        }
        case 1811: {
          if (tag !== 14490) {
            break;
          }

          message.userAgreementUrl = reader.string();
          continue;
        }
        case 1741: {
          if (tag !== 13930) {
            break;
          }

          message.temporaryMaintenanceUrl = reader.string();
          continue;
        }
        case 1512: {
          if (tag !== 12098) {
            break;
          }

          message.personalInformationInGameUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Gateserver {
    return {
      unk1: isSet(object.unk1) ? globalThis.Boolean(object.unk1) : false,
      assetBundleUrl: isSet(object.assetBundleUrl)
        ? globalThis.String(object.assetBundleUrl)
        : isSet(object.asset_bundle_url)
        ? globalThis.String(object.asset_bundle_url)
        : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      retcode: isSet(object.retcode) ? globalThis.Number(object.retcode) : 0,
      regionName: isSet(object.regionName)
        ? globalThis.String(object.regionName)
        : isSet(object.region_name)
        ? globalThis.String(object.region_name)
        : "",
      exResourceUrl: isSet(object.exResourceUrl)
        ? globalThis.String(object.exResourceUrl)
        : isSet(object.ex_resource_url)
        ? globalThis.String(object.ex_resource_url)
        : "",
      unk2: isSet(object.unk2) ? globalThis.Boolean(object.unk2) : false,
      ip: isSet(object.ip) ? globalThis.String(object.ip) : "",
      luaUrl: isSet(object.luaUrl)
        ? globalThis.String(object.luaUrl)
        : isSet(object.lua_url)
        ? globalThis.String(object.lua_url)
        : "",
      privacyInGameUrl: isSet(object.privacyInGameUrl)
        ? globalThis.String(object.privacyInGameUrl)
        : isSet(object.privacy_in_game_url)
        ? globalThis.String(object.privacy_in_game_url)
        : "",
      gridFightGameRefCdnUrl: isSet(object.gridFightGameRefCdnUrl)
        ? globalThis.String(object.gridFightGameRefCdnUrl)
        : isSet(object.grid_fight_game_ref_cdn_url)
        ? globalThis.String(object.grid_fight_game_ref_cdn_url)
        : "",
      loginWhiteMsg: isSet(object.loginWhiteMsg)
        ? globalThis.String(object.loginWhiteMsg)
        : isSet(object.login_white_msg)
        ? globalThis.String(object.login_white_msg)
        : "",
      unk11: isSet(object.unk11) ? globalThis.Boolean(object.unk11) : false,
      gameStartCustomerServiceUrl: isSet(object.gameStartCustomerServiceUrl)
        ? globalThis.String(object.gameStartCustomerServiceUrl)
        : isSet(object.game_start_customer_service_url)
        ? globalThis.String(object.game_start_customer_service_url)
        : "",
      unk3: isSet(object.unk3) ? globalThis.Boolean(object.unk3) : false,
      unk4: isSet(object.unk4) ? globalThis.Boolean(object.unk4) : false,
      unk10: isSet(object.unk10) ? globalThis.Boolean(object.unk10) : false,
      unk5: isSet(object.unk5) ? globalThis.Boolean(object.unk5) : false,
      unk6: isSet(object.unk6) ? globalThis.Boolean(object.unk6) : false,
      unk14: isSet(object.unk14) ? globalThis.Boolean(object.unk14) : false,
      unk13: isSet(object.unk13) ? globalThis.Boolean(object.unk13) : false,
      unk7: isSet(object.unk7) ? globalThis.Boolean(object.unk7) : false,
      unk8: isSet(object.unk8) ? globalThis.Boolean(object.unk8) : false,
      unk15: isSet(object.unk15) ? globalThis.Boolean(object.unk15) : false,
      unk16: isSet(object.unk16) ? globalThis.Boolean(object.unk16) : false,
      ifixVersion: isSet(object.ifixVersion)
        ? globalThis.String(object.ifixVersion)
        : isSet(object.ifix_version)
        ? globalThis.String(object.ifix_version)
        : "",
      mdkResVersion: isSet(object.mdkResVersion)
        ? globalThis.String(object.mdkResVersion)
        : isSet(object.mdk_res_version)
        ? globalThis.String(object.mdk_res_version)
        : "",
      unk12: isSet(object.unk12) ? globalThis.Boolean(object.unk12) : false,
      baseAssetBundleVersionUpdateUrl: isSet(object.baseAssetBundleVersionUpdateUrl)
        ? globalThis.String(object.baseAssetBundleVersionUpdateUrl)
        : isSet(object.base_asset_bundle_version_update_url)
        ? globalThis.String(object.base_asset_bundle_version_update_url)
        : "",
      ifixUrl: isSet(object.ifixUrl)
        ? globalThis.String(object.ifixUrl)
        : isSet(object.ifix_url)
        ? globalThis.String(object.ifix_url)
        : "",
      unk9: isSet(object.unk9) ? globalThis.Boolean(object.unk9) : false,
      ClientSecretKey: isSet(object.ClientSecretKey) ? globalThis.String(object.ClientSecretKey) : "",
      ipv6Address: isSet(object.ipv6Address)
        ? globalThis.String(object.ipv6Address)
        : isSet(object.ipv6_address)
        ? globalThis.String(object.ipv6_address)
        : "",
      preDownload: isSet(object.preDownload)
        ? globalThis.String(object.preDownload)
        : isSet(object.pre_download)
        ? globalThis.String(object.pre_download)
        : "",
      rogueTournBuildRefApiReqColorHeaderValue: isSet(object.rogueTournBuildRefApiReqColorHeaderValue)
        ? globalThis.String(object.rogueTournBuildRefApiReqColorHeaderValue)
        : isSet(object.rogue_tourn_build_ref_api_req_color_header_value)
        ? globalThis.String(object.rogue_tourn_build_ref_api_req_color_header_value)
        : "",
      gridFightGameRefColorHeaderValue: isSet(object.gridFightGameRefColorHeaderValue)
        ? globalThis.String(object.gridFightGameRefColorHeaderValue)
        : isSet(object.grid_fight_game_ref_color_header_value)
        ? globalThis.String(object.grid_fight_game_ref_color_header_value)
        : "",
      rogueTournBuildRefApiReqColorHeaderKey: isSet(object.rogueTournBuildRefApiReqColorHeaderKey)
        ? globalThis.String(object.rogueTournBuildRefApiReqColorHeaderKey)
        : isSet(object.rogue_tourn_build_ref_api_req_color_header_key)
        ? globalThis.String(object.rogue_tourn_build_ref_api_req_color_header_key)
        : "",
      rogueTournBuildRefH5Url: isSet(object.rogueTournBuildRefH5Url)
        ? globalThis.String(object.rogueTournBuildRefH5Url)
        : isSet(object.rogue_tourn_build_ref_h5_url)
        ? globalThis.String(object.rogue_tourn_build_ref_h5_url)
        : "",
      rogueTournBuildRefStaticDataUrlPrefix: isSet(object.rogueTournBuildRefStaticDataUrlPrefix)
        ? globalThis.String(object.rogueTournBuildRefStaticDataUrlPrefix)
        : isSet(object.rogue_tourn_build_ref_static_data_url_prefix)
        ? globalThis.String(object.rogue_tourn_build_ref_static_data_url_prefix)
        : "",
      gridFightGameRefColorHeaderKey: isSet(object.gridFightGameRefColorHeaderKey)
        ? globalThis.String(object.gridFightGameRefColorHeaderKey)
        : isSet(object.grid_fight_game_ref_color_header_key)
        ? globalThis.String(object.grid_fight_game_ref_color_header_key)
        : "",
      customServiceUrl: isSet(object.customServiceUrl)
        ? globalThis.String(object.customServiceUrl)
        : isSet(object.custom_service_url)
        ? globalThis.String(object.custom_service_url)
        : "",
      gridFightGameRefH5Url: isSet(object.gridFightGameRefH5Url)
        ? globalThis.String(object.gridFightGameRefH5Url)
        : isSet(object.grid_fight_game_ref_h5_url)
        ? globalThis.String(object.grid_fight_game_ref_h5_url)
        : "",
      querySecurityFileUrl: isSet(object.querySecurityFileUrl)
        ? globalThis.String(object.querySecurityFileUrl)
        : isSet(object.query_security_file_url)
        ? globalThis.String(object.query_security_file_url)
        : "",
      teenagerPrivacyInGameUrl: isSet(object.teenagerPrivacyInGameUrl)
        ? globalThis.String(object.teenagerPrivacyInGameUrl)
        : isSet(object.teenager_privacy_in_game_url)
        ? globalThis.String(object.teenager_privacy_in_game_url)
        : "",
      thirdPrivacyInGameUrl: isSet(object.thirdPrivacyInGameUrl)
        ? globalThis.String(object.thirdPrivacyInGameUrl)
        : isSet(object.third_privacy_in_game_url)
        ? globalThis.String(object.third_privacy_in_game_url)
        : "",
      rogueMagicH5Url: isSet(object.rogueMagicH5Url)
        ? globalThis.String(object.rogueMagicH5Url)
        : isSet(object.rogue_magic_h5_url)
        ? globalThis.String(object.rogue_magic_h5_url)
        : "",
      userAgreementUrl: isSet(object.userAgreementUrl)
        ? globalThis.String(object.userAgreementUrl)
        : isSet(object.user_agreement_url)
        ? globalThis.String(object.user_agreement_url)
        : "",
      temporaryMaintenanceUrl: isSet(object.temporaryMaintenanceUrl)
        ? globalThis.String(object.temporaryMaintenanceUrl)
        : isSet(object.temporary_maintenance_url)
        ? globalThis.String(object.temporary_maintenance_url)
        : "",
      personalInformationInGameUrl: isSet(object.personalInformationInGameUrl)
        ? globalThis.String(object.personalInformationInGameUrl)
        : isSet(object.personal_information_in_game_url)
        ? globalThis.String(object.personal_information_in_game_url)
        : "",
    };
  },

  toJSON(message: Gateserver): unknown {
    const obj: any = {};
    if (message.unk1 !== false) {
      obj.unk1 = message.unk1;
    }
    if (message.assetBundleUrl !== "") {
      obj.assetBundleUrl = message.assetBundleUrl;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.retcode !== 0) {
      obj.retcode = Math.round(message.retcode);
    }
    if (message.regionName !== "") {
      obj.regionName = message.regionName;
    }
    if (message.exResourceUrl !== "") {
      obj.exResourceUrl = message.exResourceUrl;
    }
    if (message.unk2 !== false) {
      obj.unk2 = message.unk2;
    }
    if (message.ip !== "") {
      obj.ip = message.ip;
    }
    if (message.luaUrl !== "") {
      obj.luaUrl = message.luaUrl;
    }
    if (message.privacyInGameUrl !== "") {
      obj.privacyInGameUrl = message.privacyInGameUrl;
    }
    if (message.gridFightGameRefCdnUrl !== "") {
      obj.gridFightGameRefCdnUrl = message.gridFightGameRefCdnUrl;
    }
    if (message.loginWhiteMsg !== "") {
      obj.loginWhiteMsg = message.loginWhiteMsg;
    }
    if (message.unk11 !== false) {
      obj.unk11 = message.unk11;
    }
    if (message.gameStartCustomerServiceUrl !== "") {
      obj.gameStartCustomerServiceUrl = message.gameStartCustomerServiceUrl;
    }
    if (message.unk3 !== false) {
      obj.unk3 = message.unk3;
    }
    if (message.unk4 !== false) {
      obj.unk4 = message.unk4;
    }
    if (message.unk10 !== false) {
      obj.unk10 = message.unk10;
    }
    if (message.unk5 !== false) {
      obj.unk5 = message.unk5;
    }
    if (message.unk6 !== false) {
      obj.unk6 = message.unk6;
    }
    if (message.unk14 !== false) {
      obj.unk14 = message.unk14;
    }
    if (message.unk13 !== false) {
      obj.unk13 = message.unk13;
    }
    if (message.unk7 !== false) {
      obj.unk7 = message.unk7;
    }
    if (message.unk8 !== false) {
      obj.unk8 = message.unk8;
    }
    if (message.unk15 !== false) {
      obj.unk15 = message.unk15;
    }
    if (message.unk16 !== false) {
      obj.unk16 = message.unk16;
    }
    if (message.ifixVersion !== "") {
      obj.ifixVersion = message.ifixVersion;
    }
    if (message.mdkResVersion !== "") {
      obj.mdkResVersion = message.mdkResVersion;
    }
    if (message.unk12 !== false) {
      obj.unk12 = message.unk12;
    }
    if (message.baseAssetBundleVersionUpdateUrl !== "") {
      obj.baseAssetBundleVersionUpdateUrl = message.baseAssetBundleVersionUpdateUrl;
    }
    if (message.ifixUrl !== "") {
      obj.ifixUrl = message.ifixUrl;
    }
    if (message.unk9 !== false) {
      obj.unk9 = message.unk9;
    }
    if (message.ClientSecretKey !== "") {
      obj.ClientSecretKey = message.ClientSecretKey;
    }
    if (message.ipv6Address !== "") {
      obj.ipv6Address = message.ipv6Address;
    }
    if (message.preDownload !== "") {
      obj.preDownload = message.preDownload;
    }
    if (message.rogueTournBuildRefApiReqColorHeaderValue !== "") {
      obj.rogueTournBuildRefApiReqColorHeaderValue = message.rogueTournBuildRefApiReqColorHeaderValue;
    }
    if (message.gridFightGameRefColorHeaderValue !== "") {
      obj.gridFightGameRefColorHeaderValue = message.gridFightGameRefColorHeaderValue;
    }
    if (message.rogueTournBuildRefApiReqColorHeaderKey !== "") {
      obj.rogueTournBuildRefApiReqColorHeaderKey = message.rogueTournBuildRefApiReqColorHeaderKey;
    }
    if (message.rogueTournBuildRefH5Url !== "") {
      obj.rogueTournBuildRefH5Url = message.rogueTournBuildRefH5Url;
    }
    if (message.rogueTournBuildRefStaticDataUrlPrefix !== "") {
      obj.rogueTournBuildRefStaticDataUrlPrefix = message.rogueTournBuildRefStaticDataUrlPrefix;
    }
    if (message.gridFightGameRefColorHeaderKey !== "") {
      obj.gridFightGameRefColorHeaderKey = message.gridFightGameRefColorHeaderKey;
    }
    if (message.customServiceUrl !== "") {
      obj.customServiceUrl = message.customServiceUrl;
    }
    if (message.gridFightGameRefH5Url !== "") {
      obj.gridFightGameRefH5Url = message.gridFightGameRefH5Url;
    }
    if (message.querySecurityFileUrl !== "") {
      obj.querySecurityFileUrl = message.querySecurityFileUrl;
    }
    if (message.teenagerPrivacyInGameUrl !== "") {
      obj.teenagerPrivacyInGameUrl = message.teenagerPrivacyInGameUrl;
    }
    if (message.thirdPrivacyInGameUrl !== "") {
      obj.thirdPrivacyInGameUrl = message.thirdPrivacyInGameUrl;
    }
    if (message.rogueMagicH5Url !== "") {
      obj.rogueMagicH5Url = message.rogueMagicH5Url;
    }
    if (message.userAgreementUrl !== "") {
      obj.userAgreementUrl = message.userAgreementUrl;
    }
    if (message.temporaryMaintenanceUrl !== "") {
      obj.temporaryMaintenanceUrl = message.temporaryMaintenanceUrl;
    }
    if (message.personalInformationInGameUrl !== "") {
      obj.personalInformationInGameUrl = message.personalInformationInGameUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Gateserver>, I>>(base?: I): Gateserver {
    return Gateserver.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Gateserver>, I>>(object: I): Gateserver {
    const message = createBaseGateserver();
    message.unk1 = object.unk1 ?? false;
    message.assetBundleUrl = object.assetBundleUrl ?? "";
    message.port = object.port ?? 0;
    message.retcode = object.retcode ?? 0;
    message.regionName = object.regionName ?? "";
    message.exResourceUrl = object.exResourceUrl ?? "";
    message.unk2 = object.unk2 ?? false;
    message.ip = object.ip ?? "";
    message.luaUrl = object.luaUrl ?? "";
    message.privacyInGameUrl = object.privacyInGameUrl ?? "";
    message.gridFightGameRefCdnUrl = object.gridFightGameRefCdnUrl ?? "";
    message.loginWhiteMsg = object.loginWhiteMsg ?? "";
    message.unk11 = object.unk11 ?? false;
    message.gameStartCustomerServiceUrl = object.gameStartCustomerServiceUrl ?? "";
    message.unk3 = object.unk3 ?? false;
    message.unk4 = object.unk4 ?? false;
    message.unk10 = object.unk10 ?? false;
    message.unk5 = object.unk5 ?? false;
    message.unk6 = object.unk6 ?? false;
    message.unk14 = object.unk14 ?? false;
    message.unk13 = object.unk13 ?? false;
    message.unk7 = object.unk7 ?? false;
    message.unk8 = object.unk8 ?? false;
    message.unk15 = object.unk15 ?? false;
    message.unk16 = object.unk16 ?? false;
    message.ifixVersion = object.ifixVersion ?? "";
    message.mdkResVersion = object.mdkResVersion ?? "";
    message.unk12 = object.unk12 ?? false;
    message.baseAssetBundleVersionUpdateUrl = object.baseAssetBundleVersionUpdateUrl ?? "";
    message.ifixUrl = object.ifixUrl ?? "";
    message.unk9 = object.unk9 ?? false;
    message.ClientSecretKey = object.ClientSecretKey ?? "";
    message.ipv6Address = object.ipv6Address ?? "";
    message.preDownload = object.preDownload ?? "";
    message.rogueTournBuildRefApiReqColorHeaderValue = object.rogueTournBuildRefApiReqColorHeaderValue ?? "";
    message.gridFightGameRefColorHeaderValue = object.gridFightGameRefColorHeaderValue ?? "";
    message.rogueTournBuildRefApiReqColorHeaderKey = object.rogueTournBuildRefApiReqColorHeaderKey ?? "";
    message.rogueTournBuildRefH5Url = object.rogueTournBuildRefH5Url ?? "";
    message.rogueTournBuildRefStaticDataUrlPrefix = object.rogueTournBuildRefStaticDataUrlPrefix ?? "";
    message.gridFightGameRefColorHeaderKey = object.gridFightGameRefColorHeaderKey ?? "";
    message.customServiceUrl = object.customServiceUrl ?? "";
    message.gridFightGameRefH5Url = object.gridFightGameRefH5Url ?? "";
    message.querySecurityFileUrl = object.querySecurityFileUrl ?? "";
    message.teenagerPrivacyInGameUrl = object.teenagerPrivacyInGameUrl ?? "";
    message.thirdPrivacyInGameUrl = object.thirdPrivacyInGameUrl ?? "";
    message.rogueMagicH5Url = object.rogueMagicH5Url ?? "";
    message.userAgreementUrl = object.userAgreementUrl ?? "";
    message.temporaryMaintenanceUrl = object.temporaryMaintenanceUrl ?? "";
    message.personalInformationInGameUrl = object.personalInformationInGameUrl ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
